#include "Vehicle.hpp"

Vehicle::Vehicle(const vector<int> &route,
        const vector<double> &arr,
        const vector<double> &rem_batt,
        const vector<double> &chg_batt,
        const vector<double> &slack_t,
        const vector<double> &st,
        const vector<double> &lv,
        const vector<double> &remdist,
        const int &vehno,
        const double &cap,
        const double &cap2,
        const double &totalcost,
        const double &totalcost_wolast,
        const double &load_onbrd,
        const double &load_onbrd2,
        const double &load_pickup,
        const double &load_pickup2,
        const double &opskill,
        const double &drskill,
        const double &e_capacity,
        const double &e_initial,
        const double &e_cost,
        const double &e_margin,
        const double &time_pen,
        const double &load_pen,
        const double &load_pen2,
        const string &vtype,
        const string &etype,
        const bool &direct_flag,
        const double &starthour,
        const double &endhour,
        const int &maxvisit,
        const int &maxrotate,
        const double &depotservt,
        const int &rmpriority,
        const map<int, double> &chg_batt_dict,
        const vector<double> &delay_arr,
		const double &delay_totalcost,
		const double &delay_totalcost_wolast,
		const vector<double> &delay_rem_batt,
		const vector<double> &delay_chg_batt,
		const map<int, double> &delay_chg_batt_dict,
		const vector<double> &delay_slack_t,
        const vector<int> &takebreak,
        const bool &reserved_v_flag,
        const vector<double> &delay_remdist,
        const vector<double> &delay_lv,
        const vector<double> &delay_st):
            route(route),
            arr(arr),
            rem_batt(rem_batt),
            chg_batt(chg_batt),
            slack_t(slack_t),
            st(st),
            lv(lv),
            remdist(remdist),
            vehno(vehno),
            cap(cap),
            cap2(cap2),
            totalcost(totalcost),
            totalcost_wolast(totalcost_wolast),
            load_onbrd(load_onbrd),
            load_onbrd2(load_onbrd2),
            load_pickup(load_pickup),
            load_pickup2(load_pickup2),
            opskill(opskill),
            drskill(drskill),
            e_capacity(e_capacity),
            e_initial(e_initial),
            e_cost(e_cost),
            e_margin(e_margin),
            time_pen(time_pen),
            load_pen(load_pen),
            load_pen2(load_pen2),
            vtype(vtype),
            etype(etype),
            direct_flag(direct_flag),
            starthour(starthour),
            endhour(endhour),
            maxvisit(maxvisit),
            maxrotate(maxrotate),
            depotservt(depotservt),
            rmpriority(rmpriority),
            chg_batt_dict(chg_batt_dict),
            delay_arr(delay_arr),
		    delay_totalcost(delay_totalcost),
		    delay_totalcost_wolast(delay_totalcost_wolast),
		    delay_rem_batt(delay_rem_batt),
		    delay_chg_batt(delay_chg_batt),
		    delay_chg_batt_dict(delay_chg_batt_dict),
		    delay_slack_t(delay_slack_t),
            takebreak(takebreak),
            reserved_v_flag(reserved_v_flag),
            delay_remdist(delay_remdist),
            delay_lv(delay_lv),
            delay_st(delay_st)
            {}